=== wpkg/wpkg-js/xsd/hosts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.wpkg.org/hosts"
	elementFormDefault="unqualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.wpkg.org/hosts" xmlns:wpkg="http://www.wpkg.org/wpkg">

	<xsd:import namespace="http://www.wpkg.org/wpkg" schemaLocation="wpkg.xsd">
		<xsd:annotation>
			<xsd:documentation>Include WPKG master definition.
			</xsd:documentation>
		</xsd:annotation>
	</xsd:import>

	<xsd:element name="wpkg" type="wpkg">
		<xsd:annotation>
			<xsd:documentation>Root element for host definitions.
			</xsd:documentation>
		</xsd:annotation>
	</xsd:element>

	<xsd:complexType name="wpkg">
		<xsd:sequence minOccurs="1" maxOccurs="unbounded">
			<xsd:element name="host" type="host"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="host">
		<xsd:sequence maxOccurs="1" minOccurs="0">
			<xsd:sequence maxOccurs="1" minOccurs="0">
				<xsd:element name="condition" type="wpkg:condition">
					<xsd:annotation>
						<xsd:documentation>Define condition under which this host entry is applied.</xsd:documentation>
					</xsd:annotation></xsd:element>
			</xsd:sequence>
			<xsd:choice maxOccurs="unbounded" minOccurs="0">
				<xsd:element name="variable" type="wpkg:variable">
					<xsd:annotation>
						<xsd:documentation>Define an environment variable to be set when the host entry applies.</xsd:documentation>
					</xsd:annotation></xsd:element>
				<xsd:element name="profile" type="profileReference">
					<xsd:annotation>
						<xsd:documentation>Define profile which should be applied to matching host.</xsd:documentation>
					</xsd:annotation></xsd:element>
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>Hostname specification. It might contain regular expressions as well as well 
as IP-address ranges.

Direct match: This is tried first always. If the hostname matches exactly the 
value of 'name' this host node is applied to the machine.

IP-Ranges: format has to be specified as follows: 
start[-end].start[-end].start[-end].start[-end] examples: 192.168.1.1 
192.168.1.1-254 192.168.1-5.20-50
Only addresses of currently connected network adapters are matched, the
address a disconnected adapter used last is ignored.

Regular expressions: example: &quot;test-.*&quot; will match all machines where the 
hostname is starting with &quot;test-&quot; string.

If no name attribute exists then the host entry will always match. You can 
omit the name attribute and use extended attribute matching like hostname 
(which matches the host name only, but not IP), ipaddresses, domainname etc.
</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="profile-id" type="xsd:string"
			use="optional">
			<xsd:annotation>
				<xsd:documentation>Main profile. You can specify the applying profile as separate &quot;profile&quot; nodes 
as well but if there is only one single profile it is recommended to use the 
profile-id attribute.
</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attributeGroup ref="wpkg:HostMatch"></xsd:attributeGroup>
	</xsd:complexType>

	<xsd:complexType name="profileReference">
		<xsd:sequence maxOccurs="1" minOccurs="0">
			<xsd:element name="condition" type="wpkg:condition"></xsd:element>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>
					ID referencing to the profile defined in
					profiles.xml
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attributeGroup ref="wpkg:HostMatch"></xsd:attributeGroup>
	</xsd:complexType>
</xsd:schema>

=== wpkg/wpkg-js/examples/hosts/host-matching.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
	Assigning profiles to machines.

	The host nodes are evaluated from top to bottom and the first one whose
	attributes all match wins, unless applyMultiple is switched on in
	config.xml. Every attribute is a regular expression, anchor it with ^ and
	$ if it has to match the whole value.

	Run "cscript wpkg.js /query:l" on a machine to see the values it reports.
-->

<hosts:wpkg xmlns:hosts="http://www.wpkg.org/hosts"
	xmlns:wpkg="http://www.wpkg.org/wpkg"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.wpkg.org/hosts ../../xsd/hosts.xsd">

	<!-- A single machine, identified by the serial number of its board. -->
	<host name=".+" serial="^PF1A2B3C$" profile-id="test-bench" />

	<!-- Every machine of one model, for example to ship its drivers. -->
	<host name=".+" makemodel="^LENOVO, ThinkPad T480$" profile-id="thinkpad-t480" />

	<!--
		A machine identified by its hardware address. Useful for hosts which
		are renamed or re-imaged regularly.
	-->
	<host name=".+" macaddresses="^00:1A:2B:3C:4D:5E$" profile-id="kiosk" />

	<!-- Everything in the branch office network. -->
	<host name=".+" ipaddresses="^10\.20\..+" profile-id="branch-office" />

	<!-- Every 64 bit server of the domain which is in the group "Servers". -->
	<host name=".+" os="Microsoft Windows Server.+" architecture="x64"
		domainname="^example\.local$" groups="^Servers$" profile-id="server" />

	<!-- Machines which announce themselves through an environment variable. -->
	<host name=".+" environment="WPKG_ROLE=^developer$" profile-id="developer" />

	<!-- Anything which was not matched before. -->
	<host name=".+" profile-id="default" />
</hosts:wpkg>
